### ISSUE TITLE
Require ES modules

### ISSUE THREAD

**Issue by nickserv** [nickmccurdy/eslint-config-modern#5]
The majority of polled Node users (which are probably a minority of our users) prefer ES modules for Node: https://twitter.com/nickemccurdy/status/1285537567543369728

ES modules also fix various issues like enabling strict mode without annoying `"use strict"` expressions, better tooling integration, and more standardized syntax in TypeScript (CJS modules require proprietary syntax which is very confusing). It would also be convenient for users to not have to configure ESLint for module support.

**Comment by nickmccurdy** [comment]
The majority of polled Node users (which are probably a minority of our users) prefer ES modules for Node: https://twitter.com/nickemccurdy/status/1285537567543369728

ES modules also fix various issues like enabling strict mode without annoying `"use strict"` expressions, better tooling integration, and more standardized syntax in TypeScript (CJS modules require proprietary syntax which is very confusing). This is definitely a change we should make, but I'm probably going to wait until other rules are updated and we're ready to use ES modules internally (either by requiring modern Node versions or adding a build tool).

**Comment by nickmccurdy** [comment]
It would also be convenient for users to not have to configure ESLint for module support
